# Generated by Django 3.0.2 on 2021-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emailID', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('IsAdmin', models.BooleanField()),
                ('IsDoctor', models.BooleanField()),
            ],
        ),
    ]
