# Generated by Django 3.0.2 on 2021-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
