# Generated by Django 3.0.2 on 2021-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210228_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSymptomRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=50)),
                ('searchcount', models.IntegerField(default=0)),
            ],
        ),
    ]
