# Generated by Django 3.0.2 on 2021-03-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_searchdiseaseresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasetreatment',
            old_name='duratioin',
            new_name='duration',
        ),
    ]
