# Generated by Django 3.0.2 on 2021-03-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_answers_pharmacy_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.IntegerField(default=380001),
        ),
    ]
