# Generated by Django 3.0.2 on 2021-03-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20210320_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='que_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Questions'),
        ),
    ]
