# Generated by Django 3.0.2 on 2021-03-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210320_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='que_text',
            field=models.CharField(default='Questions', max_length=2000),
        ),
    ]
