# Generated by Django 3.0.2 on 2021-04-12 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdiseaseresult',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchsymptomrecord',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
