# Generated by Django 3.0.2 on 2021-04-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20210412_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdiseaseresult',
            old_name='date_posted',
            new_name='searchdate',
        ),
        migrations.RenameField(
            model_name='searchsymptomrecord',
            old_name='date_posted',
            new_name='searchdate',
        ),
    ]
